### ISSUE TITLE
Consolidate on persona vs personas directory

### ISSUE THREAD

**Issue by bpolly** [wesdelp/personas#15]
We're currently putting custom persona files into `app/models/persona` although maybe we should be putting them into `app/models/personas` instead.

**Comment by bpolly** [comment]
@wesdelp you still ok with putting them into `app/models/personas` ? That's how I set it up in https://github.com/wesdelp/personas/pull/14

**Comment by wesdelp** [comment]
👍 @bpolly yeah I think that’s a good idea
